### ISSUE TITLE
Add proper permission node

### ISSUE THREAD

**Issue by mikeygio10** [ThunderDoesPlugins/StaffChat#5]
Could you make is so players cant see the  command /staffchat i get they cant use it but its annoying

DEV EDIT: add proper permission check so PMMP knows to hide the command if they dont have permission

**Comment by Thunder33345** [comment]
probably better to find a command hider plugin...
i mean i could consider but options for me just seems too hacky to consider,
i guess i wont mind if anyone want to PR it with an option to use preprocess event rather then a proper registering...

**Comment by mikeygio10** [comment]
so no

**Comment by mikeygio10** [comment]
ok

**Comment by Thunder33345** [comment]
okay i think this should do it, now only people with the root node of "staffchat" can see the command

**Comment by mikeygio10** [comment]
now your staffchat.read dont work

**Comment by Thunder33345** [comment]
please make a new issue as this is not related to this
please also be descriptive or i wont be bother fixing it as i dont know what caused it
