### ISSUE TITLE
Video!

### ISSUE THREAD

**Issue by JJBirdmanYT** [ThunderDoesPlugins/StaffChat#7]
I made a video on this plugin [here](https://youtu.be/wdwaLXjw9Xs) as it says that you might be looking for one, really good plugin btw!

**Comment by Thunder33345** [comment]
Thanks, featured!

you forgot the prefix part though
`
To chat into staff chat type your prefix followed by your message, no spaces are required
For example prefix is . so typing ".this message will be sent to staff chat" will sent that message to staff chat letting all online staff to know
`
(so you dont need to keep toggling between staff and normal chat)
